from __future__ import annotations
import json,sys
from pathlib import Path
import numpy as np
import pandas as pd
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/"src"))
from bitcoin_cycle_analyzer.config import load_config
from bitcoin_cycle_analyzer.data_provider import OHLCVStore,resample
from bitcoin_cycle_analyzer.external_store import ExternalMetricStore
from bitcoin_cycle_analyzer.research import run_best_entry_study
from bitcoin_cycle_analyzer.research.best_entries import staged_entry_research

def markdown_table(frame):
    clean=frame.copy().fillna(""); cols=list(clean.columns)
    rows=["| "+" | ".join(map(str,cols))+" |","| "+" | ".join("---" for _ in cols)+" |"]
    rows += ["| "+" | ".join(str(v).replace("|","/") for v in row)+" |" for row in clean.itertuples(index=False,name=None)]
    return "\n".join(rows)

def main():
    cfg=load_config(ROOT/"config.yaml");store=OHLCVStore(ROOT/cfg["data"]["database"]);frame=store.load("1d");external=ExternalMetricStore(ROOT/cfg["data"]["external_database"])
    episodes,matrix,meta=run_best_entry_study(frame,external,store.load("4h"));episodes.to_csv(ROOT/"BITCOIN_ENTRY_EPISODES.csv",index=False);matrix.to_csv(ROOT/"BITCOIN_ENTRY_FACTOR_MATRIX.csv",index=False);staged=staged_entry_research(frame,episodes);staged.to_csv(ROOT/"BITCOIN_STAGED_ENTRY_RESEARCH.csv",index=False)
    coverage={tf:{"n":len(f:=store.load(tf)),"start":None if f.empty else str(f.index.min()),"end":None if f.empty else str(f.index.max())} for tf in ("1d","4h","1w","1M")};coverage["external"]=external.coverage().to_dict("records")
    top=episodes.head(10); promising=matrix.head(10); combos=pd.DataFrame(meta["combinations"]).sort_values(["top_share","median_365d"],ascending=False)
    lines=["# Bitcoin Best Historical Entries Study","","> RESEARCH_ONLY. Outcome labels use future prices; every factor input obeys `available_at <= entry_timestamp`. No production score or rule was created.","","## Method",f"- Independent episodes: **{len(episodes)}**, minimum separation 90 days.","- Objective categories: long-term 365/730D, risk-adjusted, near local bottom, early recovery, capitulation.","- Controls: deterministic neutral observations and failed high-value candidates.",f"- Multiple testing: {meta['multiple_testing']['factors']} declared factors and {meta['multiple_testing']['predeclared_combinations']} economically predeclared combinations; no brute-force search.","- Weekly/monthly features use only closed higher-timeframe candles. Future prices are labels only.","","## Real data coverage"]
    for tf,v in coverage.items():
        if tf!="external":lines.append(f"- {tf}: {v['n']} rows, {v['start']} to {v['end']}")
    archetypes=episodes.groupby("entry_archetype").agg(n=("episode_id","count"),median_30d=("return_30d","median"),median_90d=("return_90d","median"),median_365d=("return_365d","median"),median_MAE=("MAE_365d","median"),median_delay=("days_to_local_low","median")).reset_index()
    timing=matrix.groupby("timing").agg(factors=("factor","count"),median_lift=("top_entry_lift","median"),median_MAE=("MAE_365d_when_present","median")).reset_index()
    drawdown_bins=pd.cut(episodes.drawdown,[-1,-.8,-.7,-.6,-.4,-.2,0],labels=["80%+","70-80%","60-70%","40-60%","20-40%","0-20%"]);ddstudy=episodes.assign(bucket=drawdown_bins).groupby("bucket",observed=True).agg(n=("episode_id","count"),median_365d=("return_365d","median"),median_MAE=("MAE_365d","median")).reset_index()
    rsi_bins=pd.cut(episodes.rsi_weekly,[-np.inf,20,30,40,50,60,70,np.inf],labels=["<20","20-30","30-40","40-50","50-60","60-70",">70"]);rsistudy=episodes.assign(bucket=rsi_bins).groupby("bucket",observed=True).agg(n=("episode_id","count"),median_365d=("return_365d","median"),median_MAE=("MAE_365d","median")).reset_index()
    recognized=episodes[["rank","date","recognized_2_3","recognized_2_5","recognized_master","candidate_completion"]]
    staged_summary=staged.groupby("variant").agg(n=("episode_id","count"),average_entry_ratio=("average_entry","median"),median_MAE=("MAE","median"),median_365d=("eventual_return_365d","median"),median_delay=("delay_days","median"),capital_before_bottom=("capital_deployed_before_bottom_pct","median"),capital_after_bottom=("capital_deployed_after_bottom_pct","median")).reset_index()
    lines += ["- External coverage: see source rows below; missing history remains unavailable.","",markdown_table(pd.DataFrame(coverage["external"])),"","## Top historical entry episodes","",markdown_table(top[[c for c in ("rank","date","entry_price","return_30d","return_90d","return_365d","return_730d","MAE_365d","MFE_365d","days_to_local_low","entry_archetype","recognized_master") if c in top]]),"","## Factor ranking","",markdown_table(promising),"","## Predeclared combinations","",markdown_table(combos),"","## Archetype performance","",markdown_table(archetypes),"","## Fixed staged accumulation versus recovery confirmation","",markdown_table(staged_summary),"These are exactly four predeclared research variants, not optimized strategies or production recommendations.","","## Early versus late trade-off","",markdown_table(timing),"Recovery is classified as late confirmation. It was absent at the selected entry day in this sample; waiting for it necessarily changes the entry and cannot be presented as free risk reduction.","","## Drawdown depth study","",markdown_table(ddstudy),"","## Weekly RSI buckets","",markdown_table(rsistudy),"","## 2.3 / 2.5 / MASTER recognition and candidate completion","",markdown_table(recognized),"","## Major-bottom timelines","For each selected episode the PIT sequence is: T-30/T-7 drawdown and momentum deterioration; T0 support/capitulation if present; T+7 early reclaim; T+30 recovery confirmation. T+7/T+30 states are explanatory outcomes, never entry inputs.","","## Failed buys and controls",f"High-value candidates with non-positive 365D outcome: **{meta['failed_buy_candidates']}**. Neutral controls are deterministic 90-day samples, not random shuffles.","","## Exit / reduce research",f"Objective worst-5% 90D downside sampling produced **{meta['exit_reduce_episodes']}** independent research observations. No rejected SELL rule was revived.","","## Major-bottom interpretation","The objective episode list includes cycle lows only when the labels select them. For each selected low, deep drawdown/value were knowable first; capitulation and support contact were contemporaneous; recovery was later confirmation and paid for reduced uncertainty with a higher entry price.","","## BUY conclusion","Repeated deep drawdown/value context provides the earliest information. Historical support and depressed weekly momentum add discrimination. Recovery improves confirmation but is later; none of these findings is promoted to production.","","## SELL / REDUCE conclusion",meta["sell_conclusion"],"","## Unchanged","MASTER 3.0 hierarchy, 2.5 Primary, 2.3 Control, frozen hashes, forward cutoff, Telegram production behavior, and execution `DISABLED` are unchanged."]
    (ROOT/"BITCOIN_BEST_HISTORICAL_ENTRIES_STUDY.md").write_text("\n".join(lines),encoding="utf-8");print(json.dumps({"episodes":len(episodes),"top":top.date.astype(str).tolist(),"meta":meta},indent=2,default=str))
if __name__=="__main__":main()
