"""Decision Rule Registry (Teil 36/37 of Auftrag 1).

Auditable, versioned catalogue of every rule this package adds. Each ID is
referenced directly in decision_engine.py's `reasons.rule_ids`, so any
DecisionState can be traced back to the exact rule that produced it.
"""

RULE_REGISTRY = [
    {"id": "DZ-001", "name": "Buy Zone Classification", "version": "1.0.0", "purpose": "Classify CONTROL 3 buy_zones into STRONG_BUY_ZONE/BUY_ZONE/WATCH_ZONE", "inputs": ["master.state.buy_zones", "macro7.actions.macro", "evidence_agreement"], "output": "zone_type", "thresholds": "confluence_count>=6 & cycle=ACCUMULATE & supporting>=3 -> STRONG_BUY_ZONE", "status": "ACTIVE", "tests": "test_decision_intelligence.py::test_zone_classification", "last_changed": "2026-08-11"},
    {"id": "DZ-002", "name": "Macro Zone Classification", "version": "1.0.0", "purpose": "Classify MACRO 7 tactical/macro/deep/extreme zones", "inputs": ["macro7.zones"], "output": "zone_type", "thresholds": "extreme_cycle -> HIGH_RISK_ZONE; support=LOW -> WATCH_ZONE; else BUY_ZONE", "status": "ACTIVE", "tests": "test_decision_intelligence.py::test_zone_classification", "last_changed": "2026-08-11"},
    {"id": "EL-004", "name": "Cycle-Elliott Consistency", "version": "1.0.0", "purpose": "Flag CONSISTENT/CONFLICT between cycle bucket and engine's actual Elliott hypothesis", "inputs": ["macro7.cycle.phase", "macro7.elliott.primary", "macro7.elliott.alternatives"], "output": "consistency", "thresholds": "keyword match against static textbook table", "status": "ACTIVE", "tests": "test_decision_intelligence.py::test_cycle_elliott_context", "last_changed": "2026-08-11"},
    {"id": "CF-001", "name": "Weekly Reclaim Confirmation", "version": "1.0.0", "purpose": "Weekly close above Elliott confirmation level", "inputs": ["macro7.elliott.primary.confirmation_level", "frame.close (weekly resample)"], "output": "weekly_reclaim", "thresholds": "close > confirmation_level", "status": "ACTIVE", "tests": "test_decision_intelligence.py::test_confirmation_engine", "last_changed": "2026-08-11"},
    {"id": "CF-002", "name": "Structure Reclaim Confirmation", "version": "1.0.0", "purpose": "Price above nearest confirmed resistance", "inputs": ["master.state.nearest_resistance"], "output": "structure_reclaim", "thresholds": "price > lower_bound", "status": "ACTIVE", "tests": "test_decision_intelligence.py::test_confirmation_engine", "last_changed": "2026-08-11"},
    {"id": "CF-003", "name": "Higher Low Confirmation", "version": "1.0.0", "purpose": "Most recent confirmed swing low above the previous one", "inputs": ["elliott_cycle.elliott.evidence.confirmed_swings"], "output": "higher_low", "thresholds": "last low price > previous low price", "status": "ACTIVE", "tests": "test_decision_intelligence.py::test_confirmation_engine", "last_changed": "2026-08-11"},
    {"id": "CF-004", "name": "Momentum Recovery Confirmation", "version": "1.0.0", "purpose": "Weekly RSI recovering above 45", "inputs": ["advanced.momentum.weekly.rsi"], "output": "momentum_recovery", "thresholds": "weekly_rsi > 45", "status": "ACTIVE", "tests": "test_decision_intelligence.py::test_confirmation_engine", "last_changed": "2026-08-11"},
    {"id": "EN-001", "name": "Entry Playbook Eligibility", "version": "1.0.0", "purpose": "Match active zone + cycle bucket + evidence agreement against 7 entry archetypes", "inputs": ["cycle_bucket", "active_zone", "evidence_agreement.supporting_count", "confirmation.triggers"], "output": "playbooks_matched", "thresholds": "see ENTRY_PLAYBOOKS in playbooks.py", "status": "ACTIVE", "tests": "test_decision_intelligence.py::test_playbook_matching", "last_changed": "2026-08-11"},
    {"id": "DE-001", "name": "High Risk Override", "version": "1.0.0", "purpose": "Force HIGH_RISK decision regardless of other evidence", "inputs": ["zones (HIGH_RISK_ZONE active)", "master5_challenger.risk.sell_off_risk"], "output": "decision=HIGH_RISK", "thresholds": "sell_off_risk in (HIGH, ELEVATED)", "status": "ACTIVE", "tests": "test_decision_intelligence.py::test_decision_engine_high_risk", "last_changed": "2026-08-11"},
    {"id": "DE-002", "name": "Take Profit Override", "version": "1.0.0", "purpose": "Force TAKE_PROFIT at confirmed distribution near resistance", "inputs": ["zones (TAKE_PROFIT_ZONE active)", "master5_challenger.risk.distribution"], "output": "decision=TAKE_PROFIT", "thresholds": "distribution in (DISTRIBUTION, DISTRIBUTION_CONFIRMED)", "status": "ACTIVE", "tests": "test_decision_intelligence.py::test_decision_engine_take_profit", "last_changed": "2026-08-11"},
    {"id": "DE-003", "name": "No Active Zone", "version": "1.0.0", "purpose": "NO_EDGE/WAIT when price is inside no structural zone", "inputs": ["active_zone"], "output": "decision in (NO_EDGE, WAIT)", "thresholds": "active_zone is None", "status": "ACTIVE", "tests": "test_decision_intelligence.py::test_decision_engine_no_edge", "last_changed": "2026-08-11"},
    {"id": "DE-004", "name": "Confirmed Entry Gate", "version": "1.0.0", "purpose": "STRONG_BUY/BUY quality gate", "inputs": ["playbooks_matched (CONFIRMED)", "hard_invalidation_breached", "evidence_agreement"], "output": "decision in (STRONG_BUY, BUY)", "thresholds": "STRONG_BUY requires zone=STRONG_BUY_ZONE, supporting>=3, contradicting=0, confirmation.met_count>=4", "status": "ACTIVE", "tests": "test_decision_intelligence.py::test_decision_engine_confirmed_buy", "last_changed": "2026-08-11"},
    {"id": "DE-005", "name": "Hard Invalidation Gate", "version": "1.0.0", "purpose": "Never issue BUY when the Elliott primary-count invalidation level is breached", "inputs": ["macro7.elliott.primary.invalidation_level", "current_price"], "output": "decision=WAIT", "thresholds": "price < invalidation_level", "status": "ACTIVE", "tests": "test_decision_intelligence.py::test_decision_engine_hard_invalidation", "last_changed": "2026-08-11"},
    {"id": "DE-006", "name": "Eligible-Not-Confirmed", "version": "1.0.0", "purpose": "ACCUMULATE/WATCH when a playbook is eligible but confirmation is missing", "inputs": ["playbooks_matched"], "output": "decision in (ACCUMULATE, WATCH)", "thresholds": "playbooks non-empty, no CONFIRMED entry_status", "status": "ACTIVE", "tests": "test_decision_intelligence.py::test_decision_engine_watch", "last_changed": "2026-08-11"},
    {"id": "DE-007", "name": "No Eligible Playbook", "version": "1.0.0", "purpose": "WATCH when zone is active but no playbook matches the current cycle bucket", "inputs": ["playbooks_matched"], "output": "decision=WATCH", "thresholds": "playbooks empty", "status": "ACTIVE", "tests": "test_decision_intelligence.py::test_decision_engine_watch", "last_changed": "2026-08-11"},
]
